---
- name: Install Arch Linux
  tags: arch_install
  hosts: arch_laptop                         # UPDATE
  gather_facts: yes
  vars_files:
    - group_vars/vault
  roles:
    - role: install_arch
    - role: cleanup_reboot
    - role: install_shell
    - role: install_compositor
