---
- name: Create /home/{{ arch_username }}/.zshrc
  when: new_shell == '/bin/zsh'
  copy:
    dest: "{{ install_root_mount_dir }}/home/{{ arch_username }}/.zshrc"
    owner: "1000"
    group: "1000"
    mode: 0644
    src: files/zshrc
