---
- name: Zsh | Testing Import Task
  debug:
    msg: Hello from zsh

- name: Zsh | Create /home/{{ arch_username }}/.zshrc
  copy:
    dest: "{{ install_root_mount_dir }}/home/{{ arch_username }}/.zshrc"
    owner: "1000"
    group: "1000"
    mode: 0644
    src: files/zshrc