---
- name: Zsh | Testing Import Task
  debug:
    msg: Hello from zsh

- name: Zsh | Install Zsh Packages
  become: yes
  when: arch_compositor == 'zsh'
  pacman:
    name:
      - zsh

- name: Zsh | Create /home/{{ arch_username }}/.zshrc
  copy:
    dest: "/home/{{ arch_username }}/.zshrc"
    mode: 0644
    src: files/zshrc