---
- name: Unmount partitions
  become: yes
  when: arch_installed is defined
  mount:
    path: "{{ item }}"
    state: unmounted
  loop: ["{{ install_boot_mount_dir }}", "{{ install_root_mount_dir }}"]
  tags: cleanup
