---
- name: Cleanup/Reboot | Import Cleanup Tasks
  import_tasks: cleanup.yaml
  when: skip_cleanup == 'no'

- name: Cleanup/Reboot | Import Reboot Tasks
  import_tasks: reboot.yaml
  when: skip_reboot == 'no'